pizzamama/pizza_project/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
]

pizzamama/pizza_project/menu/urls.py
from django.urls import path
from . import views
app_name = 'menu'

urlpatterns = [
    path('', views.index, name="index"),
]

pizzamama/pizza_project/pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("menu/", include("menu.urls")),
    path("", include("main.urls")),
]

pizzamama/pizza_project/main/models.py
from django.db import models

# Create your models here.

pizzamama/pizza_project/menu/models.py
from django.db import models


class Pizza(models.Model):
    noms = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)

    def __str__(self):
        return self.noms

pizzamama/pizza_project/main/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'main/index.html')

pizzamama/pizza_project/menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Pizza
# Create your views here.


def index(request):
   '''pizzas = Pizza.objects.all()
    pizzas_noms = [pizza.noms + " : " + str(pizza.prix) for pizza in pizzas]
    pizzas_noms_str = ", ".join(pizzas_noms)
    return HttpResponse("Les pizzas " + pizzas_noms_str)'''
   pizzas = Pizza.objects.all().order_by('noms')
   return render(request, 'menu/index.html',{"pizzas": pizzas})

pizzamama/pizza_project/main/templates/main/index.html
{%load static%}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Main page</title>
    <link rel="stylesheet" href="{%static 'main/style.css'%}">
</head>
<body>
    <div class="block">
        <img src="{%static 'main/images/main_logo.png'%}">
            <a class="lien" href="{% url 'menu:index'  %}">Aller au menu</a>
    </div>

</body>
</html>

pizzamama/pizza_project/menu/templates/menu/index.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Menu des pizzas</title>
    <link rel="stylesheet" href="{%static 'menu/style.css' %}">
</head>
<body>
     <a href="{% url 'main:index'  %}"><img id = "small_logo" src="{%static 'menu/images/small_logo.png' %}"></a>
    <div class="menu_title">
        <h1>Les pizzas</h1>
    </div>
     <div class="menu_list">
            {%for pizza in pizzas%}
              <div class="menu_list_item">
                  <span class="menu_list_title">{{pizza.noms}} </span>
                  <span class="prix">{{pizza.prix}}$</span>
                  <p class="ingredients">{{pizza.ingredients}}</p>
                  {%if pizza.vegetarienne == True %}
                    <div class="vegetarienne">VEGETARIENNE</div>
                  {%endif%}
              </div>
            {%endfor%}
     </div>
</body>
</html>